[gin]
  debug = true

[auth]
  secret = "matthiola"

[nsq]
  host = "127.0.0.1"
  topic = "matthiola"
  [nsq.nsqd]
    port = 4150
  [nsq.nsqlookupd]
    port = 4161

[mysql]
  user = "root"
  password = ""
  host = "127.0.0.1"
  port = 3306
  dbname = "broker"

[etcd]
  endpoints = ["127.0.0.1:2379", "127.0.0.1:2380"]
  [etcd.keys]
    asks = "/matthiola/futures_id/asks"
    bids = "/matthiola/futures_id/bids"
    all = "/matthiola/futures_id/all"
    update = "/matthiola/futures_id/update"
