[gin]
  debug = true

[auth]
  secret = "matthiola"
  [auth.admin]
    secret = "matthiola.admin"

[nsq]
  host = "127.0.0.1"
  topic = "matthiola"
  [nsq.nsqd]
    port = 4150
  [nsq.nsqlookupd]
    port = 4161

[mysql]
  user = "root"
  password = "rudeiger0022"
  host = "127.0.0.1"
  port = 3306
  dbname = "broker"

[etcd]
  endpoints = ["127.0.0.1:2379", "127.0.0.1:2380"]
  [etcd.keys]
    # Order Book
    orderbook = "/matthiola/orderbook/asks"
    asks = "/matthiola/orderbook/asks/futures_id"
    bids = "/matthiola/orderbook/bids/futures_id"
    # Trade
    update = "/matthiola/update"
    trade = "/matthiola/update/futures_id"
