[gin]
  debug = true
  port = 8080

[websocket]
  port = 8000

[auth]
  secret = "matthiola"

[nsq]
  host = "127.0.0.1"
  topic = "matthiola"
  [nsq.nsqd]
    port = 4150
  [nsq.nsqlookupd]
    port = 4161

[mysql]
  user = "root"
  password = ""
  host = "127.0.0.1"
  port = 3306
  dbname = "broker"

[etcd]
  endpoints = ["127.0.0.1:2379"]
  [etcd.keys]
    trades = "/matthiola/trades/trade_id"
    futures = "/matthiola/futures/futures_id"
