[gin]
  debug = true
  port = 8080

[auth]
  secret = "matthiola"

[nsq]
  host = "127.0.0.1"
  topic = "matthiola"
  [nsq.nsqd]
    port = 4150
  [nsq.nsqlookupd]
    port = 4161

[mysql]
  user = "root"
  password = ""
  host = "127.0.0.1"
  port = 3306
  dbname = "broker"
